version=1.0.2
group=princ.tdendcrystal
java_version=25

minecraft_version=26.1
minecraft_version_min=26.1
minecraft_version_max=26.2
mod_name=3D End Crystal
mod_author=PrincParshia
mod_id=td_end_crystal
license=All Rights Reserved
credits=
description=3D and Animated End Crystal!
minecraft_version_range=[26.1, 26.3)
neo_form_version=26.1-1
#neo_form_version=26.2-2

fabric_version=0.155.2+26.1.2
#fabric_version=0.157.0+26.2
fabric_loader_version=0.19.2

neoforge_version=26.1.0.19-beta
#neoforge_version=26.2.0.57
neoforge_loader_version_range=[4,)

org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
